import os, re

site_dir = r"d:\Future Tech Companies\Grounds Maintenance Services\AR-Grounds\argrounds-website\argrounds-final\admin"

for f in os.listdir(site_dir):
    if f.endswith('.html'):
        path = os.path.join(site_dir, f)
        with open(path, 'r', encoding='utf-8') as file:
            html = file.read()
        
        # We need to replace the colors ONLY inside the <svg class="brand-icon"...> and <svg class="brand-text"...> blocks.
        # But wait, there are no other SVGs in the admin pages with these exact hex codes? Let's be safe and just replace it globally.
        # Since these are specific brand dark green hexes, it is safe to replace them globally in the file.
        # Although wait, maybe `#23432c` was used in `admin.css`? No, we just grepped admin.css and it uses hexes like `#1a6b3c`.
        
        # In SVG definitions generated by illustrator:
        # .st0 { fill: #23432c; } -> .st0 { fill: #ffffff; }
        # .st2 { fill: #526c3d; } -> .st2 { fill: #7fe8a2; }
        # And in the <path style="fill: #23432c;" /> text code.
        
        html = html.replace('#23432c', '#ffffff')
        html = html.replace('#526c3d', '#7fe8a2')
        
        with open(path, 'w', encoding='utf-8') as file:
            file.write(html)
        print(f"Recolored admin svgs in: {f}")
